[book]
title = "ReqMD"
authors = ["Ben Falk"]
src = "docs"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/benfalk/req_md"
no-section-label = true

[preprocessor.anchors-aweigh]
