[workspace]
resolver = "3"
members = ["crates/req_md", "crates/reqmd_core"]

[workspace.dependencies]

#
#  ## Dependencies to Remove:
#
json = "0.12.0"
dotenv = "0.15.0"
atty = "0.2"
comrak = "0.40"

#
#  ## Dependencies to Keep:
#
clap = { version = "4.1.0", features = ["derive"] }
reqwest = { version = "0.12", features = ["blocking"] }
regex = "1"
url = "2.1"
