[package]
name = "reqmd_core"
version = "0.1.0"
edition = "2024"

[features]
default = []
serde = ["serde/derive", "reqmd_http/serde", "url/serde", "uuid/serde"]

[dependencies]
bon.workspace = true
reqmd_http = { path = "../reqmd_http" }
reqmd_markdown = { path = "../reqmd_markdown" }
serde = { workspace = true, optional = true }
thiserror.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
rstest.workspace = true
